const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const QuestionSchema = new Schema({
  subject: String,
  questionTopic: String,
  questionPart1: String,
  questionPart2: String,
  questionPart3: String,
  questionPart4: String,
  questionPart5: String,
  questionPart6: String,
  questionPart7: String,
  questionPart8: String,
  questionPart9: String,
  questionPart10: String,
  questionPart11: String,
  questionPart12: String,
  questionPart13: String,
  questionPart14: String,
  questionPart15: String,
  questionPart16: String,
  questionPart17: String,
  questionPart18: String,
  questionPart19: String,
  questionPart20: String,

  q2type: Boolean,
  q3type: Boolean,
  q4type: Boolean,
  q5type: Boolean,
  q6type: Boolean,
  q7type: Boolean,
  q8type: Boolean,
  q9type: Boolean,
  q10type: Boolean,
  q11type: Boolean,
  q12type: Boolean,
  q13type: Boolean,
  q14type: Boolean,
  q15type: Boolean,
  q16type: Boolean,
  q17type: Boolean,
  q18type: Boolean,
  q19type: Boolean,
  q20type: Boolean,

  answer: String,
  rows: Number,
  type: String,
  contentType: String,
  placeHolder: String,
  errorMessage: String,
  imageUrl: String,
  referenceUrl: String,
  referenceTime: String
});

module.exports = Question = mongoose.model('questions', QuestionShema);
